name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    # sometimes will stuck on Build `hap`, like: https://github.com/harmonyos-dev/aigc-harmonyos-sample/actions/runs/8078878412/job/22074563084
    timeout-minutes: 20

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      
      - name: Run my Action
        id: run-action
        uses: harmonyos-dev/setup-harmonyos-sdk@0.2.0

      - name: Build
        run: |
          # for ERROR: Unable to find 'hwsdk.dir' in 'local.properties' or 'HOS_SDK_HOME' in the system environment path.
          export HOS_SDK_HOME=$(pwd)/hwsdk
          ./node_modules/.bin/hvigor --mode module -p product=default assembleHap --no-daemon

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ohtotptoken-default-unsigned.hap
          path: entry/build/default/outputs/default/ohtotptoken-default-unsigned.hap
