name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    # sometimes will stuck on Build `hap`, like: https://github.com/harmonyos-dev/aigc-harmonyos-sample/actions/runs/8078878412/job/22074563084
    timeout-minutes: 20

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      
      - name: Run my Action
        id: run-action
        uses: harmonyos-dev/setup-harmonyos-sdk@0.2.0
      - name: Unzip Release Assets
        run: |
          ls /Users/runner/harmonyos-sdk

      - name: Install HarmonyOS SDK
        run: |
          # chmod +x commandline
          # for handle Failed to request url https://devecostudio-dre.op.hicloud.com/sdkmanager/v5/hos/getSdkList
          #[                    ]0%  
          export JAVA_TOOL_OPTIONS="$JAVA_TOOL_OPTIONS -Duser.country=CN"
          
          #chmod +x /Users/runner/harmonyos-sdk/sdkmanager/bin/sdkmgr
          # 安装 HarmonyOS SDK
          /Users/runner/harmonyos-sdk/command-line-tools/sdkmanager/bin/sdkmgr install toolchains:12 OpenHarmony/toolchains:12 --accept-license
          # get current dir and export to HOS_SDK_HOME

      - name: Create OHPM package.json file
        run: |
          npm init -y
          npm config set @ohos:registry=https://repo.harmonyos.com/npm/
          npm install @ohos/hvigor@2.4.2 @ohos/hvigor-ohos-plugin@2.4.2
      - name: Build
        run: |
          # for ERROR: Unable to find 'hwsdk.dir' in 'local.properties' or 'HOS_SDK_HOME' in the system environment path.
          export HOS_SDK_HOME=$(pwd)/hwsdk
          ./node_modules/.bin/hvigor --mode module -p product=default assembleHap --no-daemon

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ohtotptoken-default-unsigned.hap
          path: entry/build/default/outputs/default/ohtotptoken-default-unsigned.hap
